const express = require("express").Router();
const usercontroller = require("../adminController/userController");
const middlewarecontroller = require("../adminController/middlewareController");
express.get("/", middlewarecontroller.verifyTokenAndAdmin, usercontroller.GetUser);
express.get("/create", middlewarecontroller.verifyTokenAndAdmin, usercontroller.GetCreateUser);
express.post("/create", middlewarecontroller.verifyTokenAndAdmin, usercontroller.PostCreateUser);
express.get("/update/:id", middlewarecontroller.verifyTokenAndAdmin, usercontroller.GetUpdateUser);
express.post("/update/:id", middlewarecontroller.verifyTokenAndAdmin, usercontroller.PostUpdateUser);
express.get("/updateAdmin/", middlewarecontroller.verifyTokenAndAdmin, usercontroller.GetUpdateAdmin);
express.post("/updateAdmin/", middlewarecontroller.verifyTokenAndAdmin, usercontroller.PostUpdateAdmin);
module.exports = express;
